# START ::: Arguments and Environment Variables =============================
FROM mariadb:10.6.16

# Your additional commands

# ARG GID
# ARG UID
# ARG ORG_DIR
# ARG APPUSR
# ARG APPGRP
# ARG WUI_PROJ_PATH

#RUN sleep 100

# RUN apt-get update # dont know why this breaks the db installation 
# RUN apt-get install -y mysql-client # dont know why this breaks the db installation

# RUN apt-get update && apt-get install -y mysql-client
# STOP ::: Arguments and Environment Variables =============================
